### ISSUE TITLE
InvalidArgument: account sequence mismatch, expected 12, got 11: incorrect account sequence: invalid request

### ISSUE THREAD

**Issue by kenorb** [FunctionX/fx-core#29]
```
$ fxcored tx slashing unjail --from nammy        
{"body":{"messages":[{"@type":"/cosmos.slashing.v1beta1.MsgUnjail","validator_addr":"fxvaloper1nammysjltdcuskztjh9z3ue8cz5lg43rs0wt2q"}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[{"denom":"FX","amount":"800000000000000000"}],"gas_limit":"200000","payer":"","granter":""}},"signatures":[]}

confirm transaction before signing and broadcasting [y/N]: N

$ fxcored tx slashing unjail --from nammy --dry-run
Error: rpc error: code = InvalidArgument desc = account sequence mismatch, expected 12, got 11: incorrect account sequence: invalid request

$ /usr/bin/fxcored tx staking edit-validator --chain-id dhobyghaut --from nammy --dry-run
Error: rpc error: code = InvalidArgument desc = account sequence mismatch, expected 12, got 11: incorrect account sequence: invalid request
```

> Error: rpc error: code = InvalidArgument desc = account sequence mismatch, expected 12, got 11: incorrect account sequence: invalid request

Actually not on dry run, the same error happens when I'm trying to unjail or edit the validator:

```
$ /usr/bin/fxcored tx slashing unjail --from nammy --yes
{"height":"0","txhash":"ADCBC08BC27D6C7C886ACE2810642BB963DD78392BBA86918FD003F7490861C9","codespace":"sdk","code":32,"data":"","raw_log":"account sequence mismatch, expected 12, got 11: incorrect account sequence","logs":[],"info":"","gas_wanted":"200000","gas_used":"41636","tx":null,"timestamp":""}

$ /usr/bin/fxcored tx staking edit-validator --chain-id dhobyghaut --from nammys --yes
{"height":"0","txhash":"04CA7633FFFE5D3E332FABC12E42D134082B816DE2C52D13E0F6719F595748A6","codespace":"sdk","code":32,"data":"","raw_log":"account sequence mismatch, expected 12, got 11: incorrect account sequence","logs":[],"info":"","gas_wanted":"200000","gas_used":"42486","tx":null,"timestamp":""}
```

Doesn't seems to happen on the other validator which is still active.

**Comment by kenorb** [comment]
I think the instance become corrupted, I'll re-setup from scratch again.

```
+ /usr/bin/fxcored start
panic: failed to write batch: leveldb/table: corruption on data-block (pos=2062411): snappy: corrupt input [file=708795.ldb]

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/store/iavl.(*Store).Commit(0xc0012ea580, 0x0, 0x0, 0x0, 0x0)
	github.com/cosmos/cosmos-sdk@v0.42.4/store/iavl/store.go:113 +0x1ed
github.com/cosmos/cosmos-sdk/store/rootmulti.commitStores(0x2bcef, 0xc0002ef8c0, 0x0)
	github.com/cosmos/cosmos-sdk@v0.42.4/store/rootmulti/store.go:978 +0x1f0
github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).Commit(0xc0012365a0, 0x2bcef, 0x0, 0xc005954000, 0x80000000)
	github.com/cosmos/cosmos-sdk@v0.42.4/store/rootmulti/store.go:350 +0x6b
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Commit(0xc00121e000, 0x0, 0x0, 0x0, 0x0)
	github.com/cosmos/cosmos-sdk@v0.42.4/baseapp/abci.go:293 +0x27c
github.com/tendermint/tendermint/abci/client.(*localClient).CommitSync(0xc000df6900, 0x0, 0x0, 0x0)
	github.com/tendermint/tendermint@v0.34.9/abci/client/local_client.go:258 +0xab
github.com/tendermint/tendermint/proxy.(*appConnConsensus).CommitSync(0xc000ce3e10, 0x0, 0x0, 0x10333ef)
	github.com/tendermint/tendermint@v0.34.9/proxy/app_conn.go:93 +0x33
github.com/tendermint/tendermint/state.(*BlockExecutor).Commit(0xc002ca91f0, 0xb, 0x0, 0xc002a39258, 0x7, 0xc002a39270, 0xa, 0x1, 0x2bcef, 0xc0012555e0, ...)
	github.com/tendermint/tendermint@v0.34.9/state/execution.go:228 +0x244
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc002ca91f0, 0xb, 0x0, 0xc002a39258, 0x7, 0xc002a39270, 0xa, 0x1, 0x2bcef, 0xc0012555e0, ...)
	github.com/tendermint/tendermint@v0.34.9/state/execution.go:180 +0x725
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(0xc0016504a0, 0xb, 0x0, 0xc002a39258, 0x7, 0xc002a39270, 0xa, 0x1, 0x2bcee, 0xc002a48100, ...)
	github.com/tendermint/tendermint@v0.34.9/consensus/replay.go:503 +0x292
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc0016504a0, 0xb, 0x0, 0xc002a39258, 0x7, 0xc002a39270, 0xa, 0x1, 0x2bcee, 0xc002a48100, ...)
	github.com/tendermint/tendermint@v0.34.9/consensus/replay.go:416 +0xd79
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0016504a0, 0x241d908, 0xc0001a95f0, 0x2, 0x0)
	github.com/tendermint/tendermint@v0.34.9/consensus/replay.go:268 +0x458
github.com/tendermint/tendermint/node.doHandshake(0x24193b8, 0xc000ce3a30, 0xb, 0x0, 0xc002a39258, 0x7, 0xc002a39270, 0xa, 0x1, 0x2bcee, ...)
	github.com/tendermint/tendermint@v0.34.9/node/node.go:293 +0x1d8
github.com/tendermint/tendermint/node.NewNode(0xc001137680, 0x23f9c00, 0xc001237220, 0xc0012eb090, 0x23c13a0, 0xc002d60018, 0xc0012eb100, 0x21a26c0, 0xc0012eb210, 0x24037e8, ...)
	github.com/tendermint/tendermint@v0.34.9/node/node.go:700 +0x1ee5
```

**Comment by kenorb** [comment]
After data rsync, everything works fine.

**Comment by kenorb** [comment]
> panic: failed to write batch: leveldb/table: corruption on data-block

This happened again:

```
+ /usr/bin/fxcored start
panic: failed to write batch: leveldb/table: corruption on data-block (pos=1569064): checksum mismatch, want=0xe2de5bba got=0xc90779d8 [file=17479029.ldb]

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/store/iavl.(*Store).Commit(0xc0014dcfc0)
	github.com/cosmos/cosmos-sdk@v0.42.4/store/iavl/store.go:113 +0x165
github.com/cosmos/cosmos-sdk/store/rootmulti.commitStores(0x36d352, 0xc002bef260)
	github.com/cosmos/cosmos-sdk@v0.42.4/store/rootmulti/store.go:978 +0x198
github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).Commit(0xc000154500)
	github.com/cosmos/cosmos-sdk@v0.42.4/store/rootmulti/store.go:350 +0x6f
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Commit(0xc00060b380)
	github.com/cosmos/cosmos-sdk@v0.42.4/baseapp/abci.go:293 +0x229
github.com/tendermint/tendermint/abci/client.(*localClient).CommitSync(0xc0002ff4a0)
	github.com/tendermint/tendermint@v0.34.9/abci/client/local_client.go:258 +0xb6
github.com/tendermint/tendermint/proxy.(*appConnConsensus).CommitSync(0x2f851f0)
	github.com/tendermint/tendermint@v0.34.9/proxy/app_conn.go:93 +0x22
github.com/tendermint/tendermint/state.(*BlockExecutor).Commit(_, {{{0xb, 0x0}, {0xc001a2aa68, 0x7}}, {0xc001a2aa80, 0x6}, 0x1, 0x36d352, {{0xc005211a40, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.9/state/execution.go:228 +0x269
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc001a2aa68, 0x7}}, {0xc001a2aa80, 0x6}, 0x1, 0x36d352, {{0xc005211a40, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.9/state/execution.go:180 +0x6ee
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0xc001a2aa68, 0x7}}, {0xc001a2aa80, 0x6}, 0x1, 0x36d351, {{0xc001a320c0, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.9/consensus/replay.go:503 +0x23c
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0xc001a2aa68, 0x7}}, {0xc001a2aa80, 0x6}, 0x1, 0x36d351, {{0xc001a320c0, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.9/consensus/replay.go:416 +0x7ae
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc001854510, {0x2064428, 0xc000628340})
	github.com/tendermint/tendermint@v0.34.9/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0xc001a2aa68, 0x7}}, {0xc001a2aa80, 0x6}, 0x1, 0x36d351, ...}, ...)
	github.com/tendermint/tendermint@v0.34.9/node/node.go:293 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc001185a40, {0x2014530, 0xc001291220}, 0xc0014dd190, {0x1ff56e0, 0xc0065a5068}, 0xc00012b200, 0x0, 0xc0014dd310, {0x20381c8, ...}, ...)
	github.com/tendermint/tendermint@v0.34.9/node/node.go:700 +0x578
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x203f848, 0xc0010a68f0}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.42.4/server/start.go:244 +0x625
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc0011c6780, {0x2f851f0, 0x0, 0x0})
	github.com/cosmos/cosmos-sdk@v0.42.4/server/start.go:120 +0x168
github.com/spf13/cobra.(*Command).execute(0xc0011c6780, {0x2f851f0, 0x0, 0x0})
	github.com/spf13/cobra@v1.1.3/command.go:852 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc00119c500)
	github.com/spf13/cobra@v1.1.3/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.1.3/command.go:890
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x419125, {0xc0010a2fc0, 0x14})
	github.com/cosmos/cosmos-sdk@v0.42.4/server/cmd/execute.go:36 +0x1d0
main.main()
	github.com/functionx/fx-core/cmd/fxcored/main.go:13 +0x2c
```
