### ISSUE TITLE
panic: Failed to start consensus state: found signature from the same key

### ISSUE THREAD

**Issue by kenorb** [FunctionX/fx-core#33]
This error happened on Testnet-1.1 when upgrading and applying EVM configuration.

```
3:28PM ERR dialing failed (attempts: 1): self ID<0199e968b5e4c2a6650f9267648ce10f94888593> addr={"id":"0199e968b5e4c2a6650f9267648ce10f94888593","ip":"144.91.x.x","port":26656} module=pex server=node
panic: Failed to start consensus state: found signature from the same key

conS:
ConsensusState

conR:
ConsensusReactor

goroutine 166 [running]:
github.com/tendermint/tendermint/consensus.(*Reactor).SwitchToConsensus(_, {{{0xb, 0x0}, {0xc0040fbca8, 0x7}}, {0xc0040fbd00, 0xa}, 0x1, 0x5da53, {{0xc0014985e0, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.9/consensus/reactor.go:129 +0x247
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000c35a40, 0x0)
	github.com/tendermint/tendermint@v0.34.9/blockchain/v0/reactor.go:328 +0x10fd
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
	github.com/tendermint/tendermint@v0.34.9/blockchain/v0/reactor.go:110 +0x85
```

The same error repeated after few restarts, then it disappeared.

Then I've got bunch of auth errors:

> ERR dialing failed (attempts: 5): auth failure: conn.ID

My key didn't change.

Version doesn't show in the latest container image:
```
fxcored version
-
```

from `functionx/fx-core:dhobyghaut-1.1` image.

After few restarts it's running fine without panic.

**Comment by zakir-code** [comment]
Please check that `$HOME/.fxcore/config/node_key.json` and `$HOME/.fxcore/config/priv_validator_key.json` cannot be same as already running node
