### ISSUE TITLE
Error: InvalidArgument: account sequence mismatch, expected 23, got 22: incorrect account sequence: invalid request

### ISSUE THREAD

**Issue by kenorb** [FunctionX/fx-core#43]
My validator is inactive on Testnet, I've tried to unjail it, but it failed with error.

```
$ /usr/bin/fxcored tx slashing unjail --broadcast-mode block --from myvalkey --keyring-backend test --dry-run 
Error: rpc error: code = InvalidArgument desc = account sequence mismatch, expected 23, got 22: incorrect account sequence: invalid request

$ /usr/bin/fxcored tx slashing unjail --broadcast-mode block --from myvalkey --keyring-backend test --yes
code: 32
codespace: sdk
data: ""
gas_used: "41639"
gas_wanted: "200000"
height: "0"
info: ""
logs: []
raw_log: 'account sequence mismatch, expected 23, got 22: incorrect account sequence'
timestamp: ""
tx: null
txhash: C4CD824685CF887126F31F19633D1EF6FE34D3AB46ED2908BFBE84DFF3A466FA
```

It returned txhash, but it's not visible in the Explorer.

- Network: Dhobyghaut

Any suggestions?

Related issue: #29, #35

**Comment by kenorb** [comment]
Upon node restart, node booted up like it nothing happened.

Then I've run the following dry command:

```
$ /usr/bin/fxcored tx slashing unjail --broadcast-mode block --from myvalkey --keyring-backend test --dry-run 
Error: rpc error: code = InvalidArgument desc = failed to execute message; message index: 0: validator not jailed; cannot be unjailed: invalid request
```

Then I've run the real command to be sure, which gave some weird error:

```
$ /usr/bin/fxcored tx slashing unjail --broadcast-mode block --from myvalkey --keyring-backend test --yes
Error: RPC error -32603 - Internal error: timed out waiting for tx to be included in a block
```

Then my validator crashed with the following stack trace:

```
7:09PM ERR Error on broadcastTxCommit err="timed out waiting for tx to be included in a block" module=rpc server=node
7:09PM ERR Error on broadcastTxCommit err="tx already exists in cache" module=rpc server=node
panic: failed to write batch: leveldb/table: Writer: keys are not in increasing order: "s/k:gravity/nag37U\x89\xb0@\xa5t\x025\x16\xea\xa2\xda\x1f\x8d\vB\r\xba\x05\x80x\xd6\xfb\xf7{/\fi\x00\xed\xdb(I\x00\x00\x00", "s/k:gravity/na:\xf1\xeaT\xa2\xb9\xa5؏6\xa6\u007fu\xec\x9fZãj\x88N\xaaa\xb9\xcde\x91\x83\x11\b\xfa\x00Zb\x83D\x00\x00\x00"

goroutine 247 [running]:
github.com/cosmos/cosmos-sdk/store/iavl.(*Store).Commit(0xc0011e85a0)
	github.com/cosmos/cosmos-sdk@v0.42.4/store/iavl/store.go:113 +0x165
github.com/cosmos/cosmos-sdk/store/rootmulti.commitStores(0xcddf5, 0xc001040270)
	github.com/cosmos/cosmos-sdk@v0.42.4/store/rootmulti/store.go:978 +0x198
github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).Commit(0xc000fc7400)
	github.com/cosmos/cosmos-sdk@v0.42.4/store/rootmulti/store.go:350 +0x6f
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Commit(0xc00121f040)
	github.com/cosmos/cosmos-sdk@v0.42.4/baseapp/abci.go:303 +0x22e
github.com/tendermint/tendermint/abci/client.(*localClient).CommitSync(0xc00002f320)
	github.com/tendermint/tendermint@v0.34.9/abci/client/local_client.go:258 +0xb6
github.com/tendermint/tendermint/proxy.(*appConnConsensus).CommitSync(0x0)
	github.com/tendermint/tendermint@v0.34.9/proxy/app_conn.go:93 +0x22
github.com/tendermint/tendermint/state.(*BlockExecutor).Commit(_, {{{0xb, 0x0}, {0xc0033ba2d8, 0x7}}, {0xc0033ba2f0, 0xa}, 0x1, 0xcddf5, {{0xc008a3d560, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.9/state/execution.go:228 +0x269
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc0033ba2d8, 0x7}}, {0xc0033ba2f0, 0xa}, 0x1, 0xcddf5, {{0xc008a3d560, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.9/state/execution.go:180 +0x6ee
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000ccb880, 0x0)
	github.com/tendermint/tendermint@v0.34.9/blockchain/v0/reactor.go:398 +0xb7b
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
	github.com/tendermint/tendermint@v0.34.9/blockchain/v0/reactor.go:110 +0x85
```

Then 2nd restart error:

```
panic: failed to write batch: leveldb/table: Writer: keys are not in increasing order: "s/k:gravity/nag37U\x89\xb0@\xa5t\x025\x16\xea\xa2\xda\x1f\x8d\vB\r\xba\x05\x80x\xd6\xfb\xf7{/\fi\x00\xed\xdb(I\x00\x00\x00", "s/k:gravity/na:\xf1\xeaT\xa2\xb9\xa5؏6\xa6\u007fu\xec\x9fZãj\x88N\xaaa\xb9\xcde\x91\x83\x11\b\xfa\x00Zb\x83D\x00\x00\x00"

goroutine 246 [running]:
github.com/cosmos/cosmos-sdk/store/iavl.(*Store).Commit(0xc001270550)
	github.com/cosmos/cosmos-sdk@v0.42.4/store/iavl/store.go:113 +0x165
github.com/cosmos/cosmos-sdk/store/rootmulti.commitStores(0xcde0e, 0xc0012c1d70)
	github.com/cosmos/cosmos-sdk@v0.42.4/store/rootmulti/store.go:978 +0x198
github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).Commit(0xc000f9f2c0)
	github.com/cosmos/cosmos-sdk@v0.42.4/store/rootmulti/store.go:350 +0x6f
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Commit(0xc001251040)
	github.com/cosmos/cosmos-sdk@v0.42.4/baseapp/abci.go:303 +0x22e
github.com/tendermint/tendermint/abci/client.(*localClient).CommitSync(0xc0010c5020)
	github.com/tendermint/tendermint@v0.34.9/abci/client/local_client.go:258 +0xb6
github.com/tendermint/tendermint/proxy.(*appConnConsensus).CommitSync(0x0)
	github.com/tendermint/tendermint@v0.34.9/proxy/app_conn.go:93 +0x22
github.com/tendermint/tendermint/state.(*BlockExecutor).Commit(_, {{{0xb, 0x0}, {0xc003313000, 0x7}}, {0xc003313010, 0xa}, 0x1, 0xcde0e, {{0xc008546160, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.9/state/execution.go:228 +0x269
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc003313000, 0x7}}, {0xc003313010, 0xa}, 0x1, 0xcde0e, {{0xc008546160, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.9/state/execution.go:180 +0x6ee
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc0002ed500, 0x0)
	github.com/tendermint/tendermint@v0.34.9/blockchain/v0/reactor.go:398 +0xb7b
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
	github.com/tendermint/tendermint@v0.34.9/blockchain/v0/reactor.go:110 +0x85
```

Then 3rd restart error:

```
panic: failed to write batch: leveldb/table: Writer: keys are not in increasing order: "s/k:gravity/nag37U\x89\xb0@\xa5t\x025\x16\xea\xa2\xda\x1f\x8d\vB\r\xba\x05\x80x\xd6\xfb\xf7{/\fi\x00\xed\xdb(I\x00\x00\x00", "s/k:gravity/na:\xf1\xeaT\xa2\xb9\xa5؏6\xa6\u007fu\xec\x9fZãj\x88N\xaaa\xb9\xcde\x91\x83\x11\b\xfa\x00Zb\x83D\x00\x00\x00"

goroutine 227 [running]:
github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).pruneStores(0xc0013aa280)
	github.com/cosmos/cosmos-sdk@v0.42.4/store/rootmulti/store.go:402 +0x20d
github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).Commit(0xc0013aa280)
	github.com/cosmos/cosmos-sdk@v0.42.4/store/rootmulti/store.go:368 +0x175
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Commit(0xc000f271e0)
	github.com/cosmos/cosmos-sdk@v0.42.4/baseapp/abci.go:303 +0x22e
github.com/tendermint/tendermint/abci/client.(*localClient).CommitSync(0xc0001819e0)
	github.com/tendermint/tendermint@v0.34.9/abci/client/local_client.go:258 +0xb6
github.com/tendermint/tendermint/proxy.(*appConnConsensus).CommitSync(0x0)
	github.com/tendermint/tendermint@v0.34.9/proxy/app_conn.go:93 +0x22
github.com/tendermint/tendermint/state.(*BlockExecutor).Commit(_, {{{0xb, 0x0}, {0xc002af69a0, 0x7}}, {0xc002af69b0, 0xa}, 0x1, 0xcde88, {{0xc006d0de00, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.9/state/execution.go:228 +0x269
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc002af69a0, 0x7}}, {0xc002af69b0, 0xa}, 0x1, 0xcde88, {{0xc006d0de00, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.9/state/execution.go:180 +0x6ee
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc00788e000, 0x0)
	github.com/tendermint/tendermint@v0.34.9/blockchain/v0/reactor.go:398 +0xb7b
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
	github.com/tendermint/tendermint@v0.34.9/blockchain/v0/reactor.go:110 +0x85
```

**Comment by kenorb** [comment]
Seems like I've to redo the validator again. Maybe the restart broke it? Is there any graceful stop of the node which I can try for the next time?

**Comment by zakir-code** [comment]
This problem looks tricky, but don't worry, let's find a way to find the problem first

1. Use `fxcored status` to query the node status, check whether the network matches, and whether catching_up is false
2. Use `fxcored query staking validator <validator address>` to query the validator status, check whether it is in jail, check status
3. If the validator is jailed, use `fxcored query slashing signing-info $(fxcored tendermint show-validator)` to query the validator signature information and check jailed_until

**Comment by kenorb** [comment]
Thanks. I've reinstalled validator's data from the snapshot and i'll try suggested steps for the next time when this happens.
