### ISSUE TITLE
panic: invariant broken: bank: total supply invariant

### ISSUE THREAD

**Issue by kenorb** [FunctionX/fx-core#8]
The following error happens on `fxcored start` right after `init fx-zakir`:

```
panic: invariant broken: bank: total supply invariant
	sum of accounts coins: 378600525462891000000000000FX
	supply.Total:          378604525462891000000000000FX


	CRITICAL please submit the following transaction:
		 tx crisis invariant-broken bank total-supply

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/crisis/keeper.Keeper.AssertInvariants({{0xc000251180, 0xb, 0x10}, {{0x205dad8, 0xc000f3f190}, 0xc00000f9f8, {0x2003568, 0xc00011ed40}, {0x20035b8, 0xc00011ede0}, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.42.4/x/crisis/keeper/keeper.go:83 +0x65b
github.com/cosmos/cosmos-sdk/x/crisis.AppModule.InitGenesis({{}, _, _}, {{0x20371c8, 0xc000054020}, {0x205b990, 0xc00009c940}, {{0x0, 0x0}, {0xc00017e1fa, ...}, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.42.4/x/crisis/module.go:149 +0x378
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x20371c8, 0xc000054020}, {0x205b990, 0xc00009c940}, {{0x0, 0x0}, {0xc00017e1fa, 0x6}, 0x0, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.42.4/types/module/module.go:304 +0x282
github.com/functionx/fx-core/app/fxcore.(*App).InitChainer(_, {{0x20371c8, 0xc000054020}, {0x205b990, 0xc00009c940}, {{0x0, 0x0}, {0xc00017e1fa, 0x6}, 0x0, ...}, ...}, ...)
	github.com/functionx/fx-core/app/fxcore/app.go:568 +0x129
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc0010f9380, {{0x34c7c87e, 0xed920b30e, 0x0}, {0xc00017e1fa, 0x6}, 0xc000116140, {0x2f851f0, 0x0, 0x0}, ...})
	github.com/cosmos/cosmos-sdk@v0.42.4/baseapp/abci.go:62 +0x415
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc000d29560, {{0x34c7c87e, 0xed920b30e, 0x0}, {0xc00017e1fa, 0x6}, 0xc000116140, {0x2f851f0, 0x0, 0x0}, ...})
	github.com/tendermint/tendermint@v0.34.9/abci/client/local_client.go:266 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc000064000, {{0x34c7c87e, 0xed920b30e, 0x0}, {0xc00017e1fa, 0x6}, 0xc000116140, {0x2f851f0, 0x0, 0x0}, ...})
	github.com/tendermint/tendermint@v0.34.9/proxy/app_conn.go:77 +0x55
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x1fcd758, 0x7}}, {0xc00017e1fa, 0x6}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.9/consensus/replay.go:319 +0xd98
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc00036e510, {0x2064068, 0xc0001c25b0})
	github.com/tendermint/tendermint@v0.34.9/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x1fcd758, 0x7}}, {0xc00017e1fa, 0x6}, 0x1, 0x0, ...}, ...)
	github.com/tendermint/tendermint@v0.34.9/node/node.go:293 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc001128280, {0x2014170, 0xc0001d6000}, 0xc00056c0f0, {0x1ff5320, 0xc00103c480}, 0xc00000f9f8, 0x0, 0xc00056c270, {0x2037e08, ...}, ...)
	github.com/tendermint/tendermint@v0.34.9/node/node.go:700 +0x578
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x203f488, 0xc000f3f190}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.42.4/server/start.go:244 +0x625
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc00104d900, {0x2f851f0, 0x0, 0x0})
	github.com/cosmos/cosmos-sdk@v0.42.4/server/start.go:120 +0x168
github.com/spf13/cobra.(*Command).execute(0xc00104d900, {0x2f851f0, 0x0, 0x0})
	github.com/spf13/cobra@v1.1.3/command.go:852 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000f35680)
	github.com/spf13/cobra@v1.1.3/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.1.3/command.go:890
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x419125, {0xc000f494e8, 0x14})
	github.com/cosmos/cosmos-sdk@v0.42.4/server/cmd/execute.go:36 +0x1d0
main.main()
	github.com/functionx/fx-core/cmd/fxcored/main.go:13 +0x2c
```

Using `functionx/fx-core:testnet-1.0` Docker container.

**Comment by kenorb** [comment]
Ok, it's because I've used `genesis.json` generated by the `init fx-zakir` command, not the one from GitHub. Works now.
