### ISSUE TITLE
panic: template: configFileTemplate:422:36: executing "configFileTemplate"

### ISSUE THREAD

**Issue by kenorb** [FunctionX/fx-core#83]
## Summary of Bug

I'm trying to change some value in the config, but I got the error instead.

```
$ grep log_level ~/.fxcore/config/config.toml
$ fxcored config config.toml log_level warn
```

Same happens when trying to change different parameters (such as `moniker`, `p2p.laddr`, `p2p.persistent_peers`, etc.).

This was working before.

And still works for other configs, e.g. `fxcored config app.toml API.Enable False`

## Version

```
$ fxcored version
HEAD-49d991f692d6662660c2c2dd9e009238f595c438
```

## Steps to Reproduce

```
$ grep log_level ~/.fxcore/config/config.toml
log_level = "warn"
$ fxcored config config.toml log_level warn
panic: template: configFileTemplate:422:36: executing "configFileTemplate" at <.Storage.DiscardABCIResponses>: nil pointer evaluating *config.StorageConfig.DiscardABCIResponses

goroutine 1 [running]:
github.com/tendermint/tendermint/config.WriteConfigFile({0xc0014bd560, 0x27}, 0xc0001f2280?)
	github.com/tendermint/tendermint@v0.34.23/config/toml.go:63 +0xd3
github.com/functionx/fx-core/v3/client/cli.(*configTomlConfig).save(0xc00143fc40)
	github.com/functionx/fx-core/v3/client/cli/config.go:110 +0x77
github.com/functionx/fx-core/v3/client/cli.RunConfigCmd(0x1f8dfa0?, {0xc0014fd260, 0x3, 0xc001273840?})
	github.com/functionx/fx-core/v3/client/cli/config.go:40 +0x242
github.com/functionx/fx-core/v3/cmd.configTomlCfgCmd.func1(0xc00111db00?, {0xc001273840?, 0x2?, 0x2?})
	github.com/functionx/fx-core/v3/cmd/config.go:80 +0xeb
github.com/spf13/cobra.(*Command).execute(0xc00111db00, {0xc0012737e0, 0x2, 0x2})
	github.com/spf13/cobra@v1.6.0/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc00118db00)
	github.com/spf13/cobra@v1.6.0/command.go:1040 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.0/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.6.0/command.go:961
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0?, {0xc00135bf20, 0x14})
	github.com/cosmos/cosmos-sdk@v0.45.11/server/cmd/execute.go:36 +0x1eb
main.main()
	github.com/functionx/fx-core/v3/cmd/fxcored/main.go:13 +0x2c
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by zakir-code** [comment]
`store.discard_abci_responses` is missing in your config file, you can use `fxcored config update` to get it back to default
