### ISSUE TITLE
client/cli/node.go : panic when querying "gas-prices" using CLI

### ISSUE THREAD

**Issue by FrenchXCore** [FunctionX/fx-core#85]
## Summary of Bug

Panic when querying "gas-prices" using CLI

## Version

release/v4.2.x-6fac022a7612b30e446568714ef4abd53a20d870

## Steps to Reproduce

run `fxcored q gas-prices` in a terminal

## Output
```
panic: interface conversion: interface {} is nil, not types.Context

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/types.UnwrapSDKContext({_, _})
        github.com/cosmos/cosmos-sdk@v0.46.12/types/context.go:328 +0x1f2
github.com/cosmos/cosmos-sdk/client/grpc/node.queryServer.Config({{{0x0, 0x0, 0x0}, {0x3667148, 0xc001521380}, 0x0, {0x0, 0x0}, {0x365a058, 0xc0015fe480}, ...}}, ...)
        github.com/cosmos/cosmos-sdk@v0.46.12/client/grpc/node/service.go:37 +0x3e
github.com/functionx/fx-core/v4/client/cli.QueryGasPricesCmd.func1(0xc000d8a900?, {0x4e132d0?, 0x0?, 0x0?})
        github.com/functionx/fx-core/v4/client/cli/node.go:26 +0x167
github.com/spf13/cobra.(*Command).execute(0xc000d8a900, {0x4e132d0, 0x0, 0x0})
        github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000549200)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.7.0/command.go:985
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x2432920?, {0x2a04e2c, 0x2}, {0xc0012215a0, 0xd})
        github.com/cosmos/cosmos-sdk@v0.46.12/server/cmd/execute.go:36 +0x20f
main.main()
        github.com/functionx/fx-core/v4/cmd/fxcored/main.go:14 +0x38

```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by fx0x55** [comment]
Thank you for your feedback on this bug, I will fix it immediately
